name: Build and Deploy

on:
  push:
    tags:
      - '**'

jobs:
  build:
    name: Build for ARM (aarch64)
    runs-on: ubuntu-latest

    outputs:
      VERSION: ${{ steps.extract_version.outputs.VERSION }}

    steps:
      # Configure QEMU to support ARM architecture
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64

      # Checkout the source code
      - name: Checkout code
        uses: actions/checkout@v4

      # Extract version from the tag
      - name: Extract version from tag
        id: vars
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      # Set up Node.js with ARM support
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Build the project
      - name: Build the project
        run: npm run build

      # Generate the binary using pkg for aarch64 (ARM 64-bit)
      - name: Create ARM binary
        run: npx pkg . --targets node18-linux-arm64 --output releases/etiquetei

      # Upload the generated binary as an artifact to be used in the next job
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: etiquetei-binary
          path: releases/etiquetei

      # Extract version from the tag and set it as output
      - name: Extract version from tag
        id: extract_version
        run: |
          VERSION="${GITHUB_REF#refs/tags/}"
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "VERSION=${VERSION}"
          echo "::set-output name=VERSION::${VERSION}"

  deploy:
    name: Deploy to Public Repo
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Checkout the public repository
      - name: Checkout public repo
        uses: actions/checkout@v4
        with:
          repository: thiagothaison/etiquetei-releases
          token: ${{ secrets.RELEASE_REPO_TOKEN }}
          path: public-repo

      # Download the binary artifact
      - name: Download binary
        uses: actions/download-artifact@v4
        with:
          name: etiquetei-binary

      # Configure Git user
      - name: Configure Git User
        run: |
          cd public-repo
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      # Setup Git LFS
      - name: Setup Git LFS in public repo
        run: |
          cd public-repo
          git lfs install
          git lfs track "etiquetei"
          git add .gitattributes
          if git diff-index --quiet HEAD; then
            echo "No changes to commit."
          else
            git commit -m "Add LFS tracking for etiquetei"
          fi

      # Copy the binary to the public repository
      - name: Copy binary to public repo
        run: |
          cp etiquetei public-repo/
          cd public-repo
          git add etiquetei
          git commit -m "bump: ${{ needs.build.outputs.VERSION }}"
          git push

      # Create a new tag and release in the releases repository
      - name: Create tag and release
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.RELEASE_REPO_TOKEN }}" \
          -d "{\"tag_name\": \"${{ needs.build.outputs.VERSION }}\",\"target_commitish\": \"main\",\"name\": \"${{ needs.build.outputs.VERSION }}\",\"body\": \"Release version ${{ needs.build.outputs.VERSION }}\",\"draft\": false,\"prerelease\": false}" \
          https://api.github.com/repos/thiagothaison/etiquetei-releases/releases
