name: Build and Deploy

on:
  push:
    tags:
      - '**'

jobs:
  build:
    name: Build for ARM (aarch64)
    runs-on: ubuntu-latest

    outputs:
      VERSION: ${{ steps.vars.outputs.VERSION }}

    steps:
      # Configura o QEMU para suportar a arquitetura ARM
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64

      # Checkout do código fonte
      - name: Checkout code
        uses: actions/checkout@v4

      # Extrair versão a partir da tag
      - name: Extract version from tag
        id: vars
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      # Instala Node.js com suporte para ARM
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Instalar dependências
      - name: Install dependencies
        run: npm install

      # Compilar a aplicação
      - name: Build the project
        run: npm run build

      # Gerar o binário usando pkg para aarch64 (ARM 64-bit)
      - name: Create ARM binary
        run: npx pkg . --targets node18-linux-arm64 --output releases/etiquetei

      # Upload do binário gerado como artefato para ser usado no próximo job
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: etiquetei-binary
          path: releases/etiquetei

      - name: LOGS
        run: |
          echo '${{ toJSON(steps.vars) }}'

  deploy:
    name: Deploy to Public Repo
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Checkout do repositório público
      - name: Checkout public repo
        uses: actions/checkout@v4
        with:
          repository: thiagothaison/etiquetei-releases
          token: ${{ secrets.RELEASE_REPO_TOKEN }}
          path: public-repo

      # Download binary
      - name: Download binary
        uses: actions/download-artifact@v4
        with:
          name: etiquetei-binary

      - name: Configure Git User
        run: |
          cd public-repo
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      # Setup Git LFS
      - name: Setup Git LFS in public repo
        run: |
          cd public-repo
          git lfs install
          git lfs track "etiquetei"
          git add .gitattributes
          if git diff-index --quiet HEAD; then
            echo "No changes to commit."
          else
            git commit -m "Add LFS tracking for etiquetei"
          fi

      # Copiar o binário para o repositório público
      - name: Copy binary to public repo
        run: |
          cp etiquetei public-repo/
          cd public-repo
          git add etiquetei
          git commit -m "bump: ${{ needs.build.outputs.VERSION }}"
          git push

      - name: LOGS
        run: |
          echo '${{ toJSON(needs.build) }}'

      # Criar uma nova tag e release no repositório de releases
      - name: Create tag and release
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.RELEASE_REPO_TOKEN }}" \
          -d "{\"tag_name\": \"${{ needs.build.outputs.VERSION }}\",\"target_commitish\": \"main\",\"name\": \"${{ needs.build.outputs.VERSION }}\",\"body\": \"Release version ${{ needs.build.outputs.VERSION }}\",\"draft\": false,\"prerelease\": false}" \
          https://api.github.com/repos/thiagothaison/etiquetei-releases/releases
